IF
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(LastSeenBy(Myself), 30)
END

IF
  ActionListEmpty()
  AttackedBy([ENEMY], 0)
  Range(LastAttackerOf(Myself), 10)
THEN
  RESPONSE #100
    AttackReevaluate(LastAttackerOf(Myself), 30)
END

IF
  ActionListEmpty()
  See([PC])
  Range(LastSeenBy(Myself), 20)
  TriggerOverride(LastSeenBy(Myself), AttackedBy([ENEMY], 0))
THEN
  RESPONSE #100
    AttackReevaluate(LastAttackerOf(LastSeenBy(Myself)), 30)
END
